jobs:
  include:
  - stage: npm audit --audit-level=moderate && test
    language: node_js
    node_js:
    - 10.13.0
    addons:
      chrome: stable
    script:
    - npm audit --audit-level=moderate
    - npm install -g @ionic/cli
    - npm install -g cordova
    - npm test
    - npm run e2e
  - stage: build
    if: tag IS blank OR tag =~ ^(?!v).+
    language: minimal
    script:
      - docker build -t shoppinglist .
      - docker run shoppinglist
  - stage: build && upload to google play
    if: tag =~ ^v
    language: minimal
    deploy:
      provider: script
      on:
        tags: true
        branch: master
      script: bash scripts/deploy.sh