jobs:
  include:
  - stage: npm audit && test
    language: node_js
    node_js:
    - 10.11.0
    addons:
      chrome: stable
    script:
    - npm audit
    - npm install -g ionic cordova
    - npm test
    - npm run e2e
  - stage: build branch
    if: type = pull_request
    language: minimal
    script:
    - docker build -t shoppinglist .
    - docker run shoppinglist
  - stage: build master
    if: type != pull_request
    language: minimal
    before_install:
    - openssl aes-256-cbc -K $encrypted_61627df7c213_key -iv $encrypted_61627df7c213_iv -in google_files.tar.enc -out google_files.tar -d
    - tar xvf google_files.tar
    script:
    - docker build -t shoppinglist --build-arg KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD -f Dockerfile.master
    - docker run shoppinglist