#!/bin/bash

npm install
npm rebuild node-sass

echo "Executing ionic cordova build android --release ..."
ionic cordova build android --release
if [ $? -ne 0 ]; then
  exit 1
fi

echo "Executing jarsigner ..."
jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore ./ShoppingList.keystore -storepass $KEYSTORE_PASSWORD /app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ShoppingList
if [ $? -ne 0 ]; then
  exit 1
fi

echo "Executing zipalign ..."
zipalign 4 /app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ShoppingList_release_signed.apk
if [ $? -ne 0 ]; then
  exit 1
fi
